name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.0.5
    - name: Build project
      run: ./gradlew assemble --stacktrace
    - name: Run instrumentation tests
      uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
      with:
        cmd: ./gradlew connectedCheck --stacktrace
        api: 33
        tag: default
        abi: x86
